#!/usr/bin/env python3
"""Apply triage-sentry REVIEW verdicts — the deterministic review-side writer.

Reads a verdicts JSON file (list produced by workflow.js) and, per disposition:
  - Archive          -> Sentry: `issue archive --until auto` (re-opens on a spike) + note.
  - Resolve          -> Sentry: `issue resolve` + note.
  - Escalate         -> Jira: create/reuse BAC Bug (cap-exempt), set AI: fields (suitability forced to
                        Human-only so the auto-fixer skips it), labels sentry+sentry-escalated, High
                        priority, best-effort transition to Escalated, native Jira link.
                        Sentry: set priority + assign triage team + note.
  - Develop          -> Sentry: assign `ai-triage` team + priority, and post the verdict (brief + score) as
                        a marker-delimited comment ON the issue. No local queue — `promote` reads it back
                        off Sentry later, within budget.
  - Silence-in-code  -> same verdict comment (Agent-ready code-suppression brief) + assign `ai-triage`;
                        Sentry: `issue archive` (forever) to stop the noise now.

Sentry auth + REST go through the authenticated `sentry` CLI (`sentry api`, `sentry issue ...`) — no
token env var. Jira reads/comments/transitions/create use `acli`; field/label/priority writes use the
Jira REST API. Every Sentry note + Jira comment starts with the AI disclaimer. Nothing writes on --dry-run.

Usage:
  python3 apply_review.py verdicts.json [--dry-run] [--field-map FILE] [--jira-env FILE]
          [--keep-score] [--no-transition]
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _common as C  # noqa: E402

DISCLAIMER = "> *This was generated by AI during triage.*"


def sentry_url(fmap, short_id):
    return f'{fmap["sentry_base_url"]}/issues/{short_id}/'


def note_body(verdict, fmap, *, extra=""):
    v = verdict
    imp = v.get("impact") or {}
    base = v.get("sentryNote") or ""
    if not base.lstrip().startswith(">"):
        base = (
            f"{DISCLAIMER}\n\n"
            f"AI TRIAGE — {v['disposition']}\n"
            f"Value: {v.get('value')} | Effort: {v.get('effort')} | Confidence: {v.get('confidence')} | "
            f"Users: {imp.get('usersAffected', '?')} | Events: {imp.get('eventCount', '?')}\n\n"
            f"{base}"
        )
    elif not base.startswith(DISCLAIMER):
        base = f"{DISCLAIMER}\n\n{base}"
    if extra:
        base = f"{base}\n\n{extra}"
    return C.strip_volatile_refs(base)


def sentry_mark(numeric, *, priority=None, assign=None):
    """Set priority (reliable) then assignment (best-effort). Returns a short status string."""
    parts = []
    if priority:
        rc, out = C.sentry_update_issue(numeric, {"priority": priority})
        parts.append("prio ok" if rc == 0 else f"prio FAIL({out[:80]})")
    if assign:
        rc, out = C.sentry_update_issue(numeric, {"assignedTo": assign})
        parts.append("assign ok" if rc == 0 else f"assign skip({out[:60]})")
    return ", ".join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("verdicts")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--keep-score", action="store_true")
    ap.add_argument("--no-transition", action="store_true")
    ap.add_argument("--field-map", default=C.default_config_path(),
                    help="central triage config (default: <repo-root>/.claude/triage-config.json)")
    ap.add_argument("--project", default="api",
                    help="project key in the config's 'projects' map (e.g. api/web-admin/flutter-app)")
    ap.add_argument("--jira-env", default="~/.config/hoopit/jira.env")
    args = ap.parse_args()

    local = os.path.join(C.repo_root(), ".claude", "local", "triage-sentry")
    cfg = C.load_field_map(args.field_map)
    fmap = C.resolve_project(cfg, args.project)
    verdicts = json.load(open(args.verdicts))
    if isinstance(verdicts, dict):
        verdicts = verdicts.get("result", verdicts.get("verdicts", [verdicts]))

    jira_auth = None
    integration_id = fmap.get("jira_integration_id")
    if not args.dry_run:
        jira_auth = C.require_jira_env(args.jira_env)
        if not C.sentry_auth_ok():
            sys.exit("FATAL: `sentry` CLI is not authenticated — run `sentry auth login`.")

    base = fmap["jira_base_url"]
    pmap = fmap["priority_map"]
    archive_until = fmap.get("archive_until", {})
    failures = 0
    counts = {}

    for v in verdicts:
        disp = v.get("disposition")
        short = v.get("sentryShortId", "<no-id>")
        numeric = v.get("sentryNumericId")
        counts[disp] = counts.get(disp, 0) + 1
        score = v.get("priorityScore") if args.keep_score else C.priority_score(v)
        prio = pmap.get(v.get("value"))

        if disp == "Archive":
            if args.dry_run:
                print(f"{short}: DRY Archive -> `sentry issue archive {short} --until auto` + note")
                continue
            rc, out = C.sentry_archive(short, until=archive_until.get("Archive", "auto"))
            nrc, _ = C.sentry_add_note(numeric, note_body(v, fmap))
            C.ledger_append(C.ledger_path(local), short, disp)
            ok = rc == 0 and nrc == 0
            failures += 0 if ok else 1
            print(f"{short}: Archive {'ok' if ok else 'PARTIAL ' + out[:120]}")
            continue

        if disp == "Resolve":
            if args.dry_run:
                print(f"{short}: DRY Resolve -> `sentry issue resolve {short}` + note")
                continue
            rc, out = C.sentry_resolve(short)
            nrc, _ = C.sentry_add_note(numeric, note_body(v, fmap))
            C.ledger_append(C.ledger_path(local), short, disp)
            ok = rc == 0 and nrc == 0
            failures += 0 if ok else 1
            print(f"{short}: Resolve {'ok' if ok else 'PARTIAL ' + out[:120]}")
            continue

        if disp == "Escalate":
            if args.dry_run:
                print(f"{short}: DRY Escalate -> create/reuse BAC bug (Human-only, High, labels sentry+sentry-escalated) + native link; sentry prio={prio}+assign+note")
                continue
            key = v.get("existingJiraKey") or C.jira_create_bug(fmap["jira_project"], v["jiraSummary"], v["jiraDescription"])
            if not key:
                print(f"{short}: ESCALATE FAILED — could not create/find Jira issue")
                failures += 1
                continue
            body = C.build_ai_fields(v, fmap, suitability=fmap["escalate_suitability"], score=None,
                                     with_components=True, priority_name=fmap["escalate_priority"])
            C.add_labels_op(body, [fmap["sentry_label"], fmap["escalated_label"]])
            st, err = C.jira_put(base, jira_auth, key, body)
            parts = [f"jira {key} fields {'ok' if st == 204 else 'FAIL ' + str(st) + ' ' + err}"]
            if st != 204:
                failures += 1
            if not args.no_transition:
                cur = C.jira_get_status(base, jira_auth, key)
                if cur and cur not in fmap.get("protected_statuses", []) and cur != fmap["escalate_status"]:
                    rc, _ = C.jira_transition(key, fmap["escalate_status"])
                    parts.append(f"{cur}->{fmap['escalate_status']}" if rc == 0 else f"(no '{fmap['escalate_status']}' status; left {cur})")
            ok, detail = C.sentry_link_jira(numeric, key, integration_id)
            if ok:
                parts.append("native-link ok")
            else:
                C.jira_comment(key, f"{DISCLAIMER}\n\nSentry: {sentry_url(fmap, short)}")
                parts.append(f"native-link FALLBACK ({detail})")
            sentry_mark(numeric, priority=prio, assign=fmap.get("triage_assignee"))
            C.sentry_add_note(numeric, note_body(v, fmap, extra=f"Escalated to {key}: {base}/browse/{key}"))
            C.ledger_append(C.ledger_path(local), short, disp, key)
            print(f"{short}: Escalate -> {key} | {' | '.join(parts)}")
            continue

        if disp in ("Develop", "Silence-in-code"):
            if args.dry_run:
                qhint = "archive-forever+assign" if disp == "Silence-in-code" else f"assign+prio={prio}"
                print(f"{short}: DRY {disp} -> sentry {qhint} + verdict comment (score={score})")
                continue
            # The verdict rides on the Sentry issue (no local queue); assigning to ai-triage makes it
            # promote's work-list. For Silence-in-code also archive forever to stop the noise now.
            verdict_min = {
                "disposition": disp,
                "agentSuitability": v.get("agentSuitability") or "Agent-ready",
                "value": v["value"], "effort": v["effort"], "confidence": v["confidence"],
                "area": v.get("area", "API"), "priorityScore": score,
                "jiraSummary": v["jiraSummary"], "jiraDescription": v["jiraDescription"],
                "jiraBrief": v.get("jiraBrief", ""),
            }
            sentry_mark(numeric, priority=prio, assign=fmap.get("triage_assignee"))
            if disp == "Silence-in-code":
                C.sentry_archive(short, until=archive_until.get("Silence-in-code"))  # None -> forever
                extra = "Queued an Agent-ready code-suppression task; archived (forever) in Sentry."
            else:
                extra = "Queued for development; a Jira bug is created once the Sentry→Jira budget has room."
            comment = note_body(v, fmap, extra=extra) + "\n\n" + C.encode_verdict(verdict_min)
            C.sentry_add_note(numeric, comment)
            C.ledger_append(C.ledger_path(local), short, disp)
            print(f"{short}: {disp} -> assigned ai-triage + verdict comment (score={score})")
            continue

        print(f"{short}: SKIP — unknown disposition {disp!r}")
        failures += 1

    summary = ", ".join(f"{k}={n}" for k, n in sorted(counts.items()))
    print(f"\n{'DRY RUN — ' if args.dry_run else ''}{len(verdicts) - failures}/{len(verdicts)} ok | {summary}")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
