#!/usr/bin/env python3
"""Promote AI-owned Sentry issues into Jira — the deterministic, zero-LLM, stateless promote step.

There is no local queue: the work-list is whatever Sentry says is assigned to the `ai-triage` team, and
each issue carries its own verdict in a marker-delimited comment that `review` posted. So promote is a
pure function of Sentry + Jira state — it survives across machines and lost checkouts.

Per run:
  1. headroom = budget_cap - (unresolved BAC issues labelled `sentry` but NOT `sentry-escalated`).
     `resolution IS EMPTY` (Done AND Awaiting-release both carry a resolution -> don't consume budget).
  2. work-list = Sentry issues `assigned:#ai-triage !is:resolved` (covers Develop=unresolved and
     Silence-in-code=ignored). Skip any that already have a native Jira link (already promoted/escalated)
     or carry no verdict comment (review will refresh).
  3. Rank by the verdict's priorityScore; for each up to headroom: dedup Jira, create the BAC Bug,
     set AI: fields + labels, native-link from Sentry, post a Sentry note.

Moving an issue off `ai-triage` (human or ownership rule) drops it from the work-list — that's the veto;
`review` (scoped `!assigned:#ai-triage`) re-picks-it-up and re-triages. The two scopes are exact
complements, so nothing strands.

Usage:
  python3 promote_pending.py [--dry-run] [--max N] [--field-map FILE] [--jira-env FILE]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _common as C  # noqa: E402

DISCLAIMER = "> *This was generated by AI during triage.*"


def budget_jql(fmap):
    # An issue with a resolution is completed/ok (covers Done AND Awaiting release/deployment, which keep
    # an "In Progress" statusCategory but are functionally finished). So count only unresolved issues.
    return (f'project = {fmap["jira_project"]} AND labels = {fmap["sentry_label"]} '
            f'AND labels != {fmap["escalated_label"]} AND resolution IS EMPTY')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--max", type=int, default=999, help="cap promotions this run (default: headroom-limited)")
    ap.add_argument("--field-map", default=C.default_config_path(),
                    help="central triage config (default: <repo-root>/.claude/triage-config.json)")
    ap.add_argument("--project", default="api",
                    help="project key in the config's 'projects' map (e.g. api/web-admin/flutter-app)")
    ap.add_argument("--jira-env", default="~/.config/hoopit/jira.env")
    args = ap.parse_args()

    local = os.path.join(C.repo_root(), ".claude", "local", "triage-sentry")
    cfg = C.load_field_map(args.field_map)
    fmap = C.resolve_project(cfg, args.project)
    base = fmap["jira_base_url"]
    integration_id = fmap.get("jira_integration_id")
    team_slug = C.team_slug_of(fmap.get("triage_assignee"))

    if not C.sentry_auth_ok():
        sys.exit("FATAL: `sentry` CLI is not authenticated — run `sentry auth login`.")

    # 1. budget
    count = C.jira_search_count(budget_jql(fmap))
    if count is None:
        sys.exit("FATAL: could not count open Sentry-sourced Jira issues (acli search failed)")
    headroom = fmap["budget_cap"] - count
    print(f"budget: {count}/{fmap['budget_cap']} open sentry issues -> headroom {headroom}")
    if headroom <= 0:
        print("board full — promoting nothing this run")
        return

    # 2. work-list = Sentry issues assigned to ai-triage, with a parsed verdict, not already linked
    work = C.sentry_team_issues(fmap, team_slug)
    candidates = []
    for w in work:
        numeric, short = w["numericId"], w["shortId"]
        issue = C.sentry_get_issue(numeric)
        if isinstance(issue, dict) and C.sentry_has_jira_link(issue):
            continue  # already promoted or escalated
        v = C.parse_verdict_from_comments(C.sentry_list_comments(numeric))
        if not v:
            C.warn(f"{short}: assigned to {team_slug} but no verdict comment — skipping (review will refresh)")
            continue
        candidates.append((numeric, short, v))
    candidates.sort(key=lambda c: -((c[2].get("priorityScore")) or -1))
    print(f"{len(candidates)} promotable candidate(s) assigned to {team_slug}; headroom {headroom}")

    if not args.dry_run:
        jira_auth = C.require_jira_env(args.jira_env)

    budget = min(headroom, args.max)
    promoted = failures = 0

    for numeric, short, v in candidates:
        if promoted >= budget:
            break
        disp = v.get("disposition", "Develop")
        suit = v.get("agentSuitability") or "Agent-ready"
        score = v.get("priorityScore")
        labels = [fmap["sentry_label"]] + ([fmap["suppression_label"]] if disp == "Silence-in-code" else [])

        if args.dry_run:
            print(f"{short}: DRY promote -> BAC bug ({suit}, score={score}, labels={labels}) + native link")
            promoted += 1
            continue

        existing = C.jira_search_keys(f'project = {fmap["jira_project"]} AND text ~ "{short}"', limit=3)
        key = existing[0] if existing else C.jira_create_bug(fmap["jira_project"], v["jiraSummary"], v["jiraDescription"])
        if not key:
            print(f"{short}: PROMOTE FAILED — could not create/find Jira issue")
            failures += 1
            continue

        body = C.build_ai_fields(v, fmap, suitability=suit, score=score, with_components=True)
        C.add_labels_op(body, labels)
        st, err = C.jira_put(base, jira_auth, key, body)
        parts = [f"{key} fields {'ok' if st == 204 else 'FAIL ' + str(st) + ' ' + err}"]
        if st != 204:
            failures += 1

        ok, detail = C.sentry_link_jira(numeric, key, integration_id)
        if ok:
            parts.append("native-link ok")
        else:
            C.jira_comment(key, f"{DISCLAIMER}\n\nSentry: {fmap['sentry_base_url']}/issues/{short}/")
            parts.append(f"native-link FALLBACK ({detail})")
        C.sentry_add_note(numeric, f"{DISCLAIMER}\n\nPromoted to {key}: {base}/browse/{key}")
        C.ledger_append(C.ledger_path(local), short, f"{disp}->promoted", key)
        promoted += 1
        print(f"{short}: promoted -> {' | '.join(parts)}")

    print(f"\n{'DRY RUN — ' if args.dry_run else ''}promoted {promoted} (headroom {headroom}), {failures} failed")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
