#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# ── Wizard-local helpers ──────────────────────────────────────────────────

SETTINGS="${CLAUDE_SETTINGS:-$HOME/.claude/settings.json}"
CLAUDE_JSON="$HOME/.claude.json"
PLUGIN_REGISTRY="$HOME/.claude/plugins/installed_plugins.json"
STAMP="$(date +%Y%m%d-%H%M%S)"

PLANNED=()      # human-readable log of every staged change
MCP_DISABLE=()  # MCP server names to disable for this project
AGENT_MOVE=()   # agent definition files to move aside
WROTE=0         # set once anything has actually been written

if ! command -v jq >/dev/null 2>&1; then
  printf 'This wizard edits JSON settings and needs jq. Install jq, then re-run.\n' >&2
  exit 1
fi

[[ -f "$SETTINGS" ]] || { mkdir -p "$(dirname "$SETTINGS")"; printf '{}\n' > "$SETTINGS"; }
if ! jq -e . "$SETTINGS" >/dev/null 2>&1; then
  printf '%s is not valid JSON. Fix it first; this wizard will not touch it.\n' "$SETTINGS" >&2
  exit 1
fi

PENDING="$(mktemp)"
cp "$SETTINGS" "$PENDING"
trap 'rm -f "$PENDING"' EXIT

plan_note() { PLANNED+=("$1"); }

# jq_pending <jq args...> applies an edit to the staged copy of settings.json.
jq_pending() {
  local tmp; tmp=$(mktemp)
  if jq "$@" "$PENDING" > "$tmp"; then mv "$tmp" "$PENDING"; else rm -f "$tmp"; return 1; fi
}

# skill_mode NAME MODE stages a skillOverrides entry: off | user-invocable-only.
skill_mode() {
  jq_pending --arg n "$1" --arg m "$2" '.skillOverrides = ((.skillOverrides // {}) + {($n): $m})'
  plan_note "skill $1 → $2"
}

# flag KEY JSON-VALUE stages a top-level setting.
flag() {
  jq_pending --arg k "$1" --argjson v "$2" '.[$k] = $v'
  plan_note "$1 = $2"
}

current_mode() { jq -r --arg n "$1" '.skillOverrides[$n] // "on"' "$PENDING"; }

# ITEMS holds "name<TAB>hint" rows; menu renders them, pick fills PICKS.
ITEMS=()
PICKS=()

menu() {
  local i=0 row name hint mode suffix
  for row in ${ITEMS[@]+"${ITEMS[@]}"}; do
    i=$((i + 1)); name=${row%%$'\t'*}; hint=${row#*$'\t'}
    mode=$(current_mode "$name")
    if [[ "$mode" == "on" ]]; then suffix=""; else suffix=" ${RED}[$mode]${RESET}"; fi
    printf '  %s%2d%s %s%-26s%s %s%s%s%s\n' \
      "$BLUE" "$i" "$RESET" "$BOLD" "$name" "$RESET" "$DIM" "$hint" "$RESET" "$suffix"
  done
}

# pick "Prompt:" fills PICKS from a line of numbers. Empty keeps everything,
# "all" selects every row.
pick() {
  local input token n row
  PICKS=()
  printf '  %s%s%s ' "$BOLD" "$1" "$RESET"
  read -r input || true
  [[ -z "${input// /}" ]] && return 0
  if [[ "$input" == "all" ]]; then
    for row in ${ITEMS[@]+"${ITEMS[@]}"}; do PICKS+=("${row%%$'\t'*}"); done
    return 0
  fi
  for token in $input; do
    [[ "$token" =~ ^[0-9]+$ ]] || continue
    n=$token
    (( n >= 1 && n <= ${#ITEMS[@]} )) || continue
    row=${ITEMS[$((n - 1))]}
    PICKS+=("${row%%$'\t'*}")
  done
}

# triage runs the two passes every skill list gets: off, then slash-only.
triage() {
  local name
  menu
  printf '\n'
  note 'off = gone from the model AND from /slash. Numbers, space-separated; Enter keeps all.'
  pick 'Turn off:'
  for name in ${PICKS[@]+"${PICKS[@]}"}; do skill_mode "$name" off; done
  note 'slash-only = hidden from the model, still typable as /name. Costs no context per turn.'
  pick 'Slash-only:'
  for name in ${PICKS[@]+"${PICKS[@]}"}; do skill_mode "$name" user-invocable-only; done
}

# skill_name_of FILE reads the frontmatter name, falling back to the directory.
skill_name_of() {
  local file="$1" n
  n=$(sed -n '1,20p' "$file" | grep -m1 '^name:' | sed 's/^name:[[:space:]]*//' | tr -d '"' || true)
  [[ -n "$n" ]] || n=$(basename "$(dirname "$file")")
  printf '%s' "$n"
}

# skill_desc_of FILE reads the frontmatter description, trimmed to fit a row.
skill_desc_of() {
  sed -n '1,20p' "$1" | grep -m1 '^description:' \
    | sed 's/^description:[[:space:]]*//' | tr -d '"' | cut -c1-44 || true
}

# ── Stages ────────────────────────────────────────────────────────────────

# banner in the library assumes a browser-driven setup; this wizard drives local
# config files instead, so it gets its own opening frame. The library above the
# STAGES marker stays byte-identical.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Every stage shows what you have installed and asks what to drop. Nothing\n' "$DIM"
  printf '  is written until the last stage, and it backs up what it touches. Ctrl-C\n'
  printf '  any time: without that final yes, nothing has changed.%s\n' "$RESET"
  pause "Ready to start?"
}

banner "Trim Claude Code's context"

stage "What we're trimming, and your baseline"
say "Every skill, plugin skill, MCP server and big built-in tool spends context on"
say "every single turn, whether you use it or not. This wizard walks your installed"
say "inventory and turns off what you don't want."
printf '\n'
step "Nothing is written until the final stage, and your settings are backed up first."
step "In Claude Code, /context shows where your context actually goes."
step "/skills shows the live skill list for your build, and toggles them interactively."
printf '\n'
note "settings file: $SETTINGS"
note "two dials per skill: off (gone entirely) and user-invocable-only (slash-only)"
pause "Ready?"

stage "Built-in skills that ship with Claude Code"
say "These live inside the claude binary. Names are from the 2.1.x line — an override"
say "for a name your build doesn't have is a harmless no-op, so over-selecting is safe."
printf '\n'
ITEMS=(
  $'code-review\treview a diff or PR for bugs'
  $'simplify\tclean up the changed code'
  $'security-review\tsecurity pass over a branch'
  $'verify\tcheck work against what was asked'
  $'run\tlaunch the app to see a change work'
  $'init\twrite a CLAUDE.md for a repo'
  $'commit\tgit commit helper'
  $'pr\topen a pull request'
  $'commit-push-pr\tcommit, push and open a PR in one'
  $'loop\trun a prompt on a recurring interval'
  $'schedule\tcron-scheduled cloud agents'
  $'workflow-authoring\twrite multi-agent workflow scripts'
  $'update-config\tedit settings.json, hooks, permissions'
  $'keybindings-help\tcustomise keyboard shortcuts'
  $'fewer-permission-prompts\tbuild a Bash allowlist from transcripts'
  $'claude-in-chrome\tdrive Chrome, screenshots, console logs'
  $'artifact-design\tdesign published claude.ai pages'
  $'artifact-diagramming\tdiagrams inside artifacts'
  $'artifact-capabilities\truntime powers for artifact pages'
  $'artifact-pr-review\tPR review as an artifact page'
  $'dataviz\tcharts and dashboards in artifacts'
  $'whiteboard\tfree-form visual canvas'
  $'workshop\tworkshop-style documents'
  $'prototype\tthrowaway UI prototypes'
  $'claude-api\tAnthropic API and SDK reference'
  $'cowork-plugin\tcowork plugin management'
)
triage

stage "Skills synced to your Claude account"
SYNCED_ROWS=""
if [[ -d "$HOME/.claude/skills/synced" ]]; then
  while IFS= read -r f; do
    [[ -n "$f" ]] || continue
    sname=$(skill_name_of "$f")
    sdesc=$(sed -n '1,20p' "$f" | grep -m1 '^description:' | sed 's/^description:[[:space:]]*//' | tr -d '"' | cut -c1-44 || true)
    SYNCED_ROWS+="anthropic-skills:$sname"$'\t'"$sdesc"$'\n'
  done < <(find "$HOME/.claude/skills/synced" -mindepth 3 -maxdepth 3 -name SKILL.md 2>/dev/null | sort)
  SYNCED_ROWS=$(printf '%s' "$SYNCED_ROWS" | sort -u -t$'\t' -k1,1)
fi
if [[ -z "$SYNCED_ROWS" ]]; then
  say "No account-synced skills found — nothing to do here."
  pause
else
  say "These come down from your Claude account (docs, docx, pdf, pptx, xlsx and friends)."
  say "They are addressed as anthropic-skills:<name>."
  printf '\n'
  ITEMS=()
  while IFS= read -r row; do [[ -n "$row" ]] && ITEMS+=("$row"); done <<< "$SYNCED_ROWS"
  triage
fi

stage "Whole plugins"
PLUGIN_KEYS=""
[[ -f "$PLUGIN_REGISTRY" ]] && PLUGIN_KEYS=$(jq -r '.plugins | keys[]' "$PLUGIN_REGISTRY" 2>/dev/null || true)
if [[ -z "$PLUGIN_KEYS" ]]; then
  say "No installed plugins found."
  pause
else
  say "Disabling a plugin removes every skill, agent and MCP server it provides."
  say "That is the biggest single win when a plugin ships an MCP server you never call."
  printf '\n'
  ITEMS=()
  while IFS= read -r key; do
    [[ -n "$key" ]] || continue
    state=$(jq -r --arg k "$key" 'if (.enabledPlugins // {}) | has($k) then (if .enabledPlugins[$k] then "enabled" else "disabled" end) else "enabled (default)" end' "$PENDING")
    ITEMS+=("$key"$'\t'"$state")
  done <<< "$PLUGIN_KEYS"
  i=0
  for row in ${ITEMS[@]+"${ITEMS[@]}"}; do
    i=$((i + 1))
    printf '  %s%2d%s %s%-40s%s %s%s%s\n' "$BLUE" "$i" "$RESET" "$BOLD" "${row%%$'\t'*}" "$RESET" "$DIM" "${row#*$'\t'}" "$RESET"
  done
  printf '\n'
  pick 'Disable which plugins:'
  for name in ${PICKS[@]+"${PICKS[@]}"}; do
    jq_pending --arg k "$name" '.enabledPlugins = ((.enabledPlugins // {}) + {($k): false})'
    plan_note "plugin $name → disabled"
  done
fi

stage "Individual skills, one source at a time"
say "Keep a plugin but drop the skills in it you never reach for. Each source gets"
say "its own screen; numbers restart on every screen."
pause

# group_triage HEADER runs one screen of the current ITEMS.
group_triage() {
  (( ${#ITEMS[@]} )) || return 0
  _clear
  printf '\n%s%s▸ Stage %s/%s · %s%s\n\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
  triage
}

PLUGIN_LIST=()
while IFS= read -r key; do
  [[ -n "$key" ]] && PLUGIN_LIST+=("$key")
done <<< "$PLUGIN_KEYS"

if (( ${#PLUGIN_LIST[@]} )); then
  for key in "${PLUGIN_LIST[@]}"; do
    enabled=$(jq -r --arg k "$key" 'if (.enabledPlugins // {}) | has($k) then .enabledPlugins[$k] else true end' "$PENDING")
    [[ "$enabled" == "false" ]] && continue
    short=${key%%@*}
    path=$(jq -r --arg k "$key" '.plugins[$k] | sort_by(.lastUpdated // .installedAt) | last | .installPath // empty' "$PLUGIN_REGISTRY" 2>/dev/null || true)
    [[ -n "$path" && -d "$path" ]] || continue
    ITEMS=()
    seen=""
    while IFS= read -r skillfile; do
      [[ -n "$skillfile" ]] || continue
      pskill="$short:$(skill_name_of "$skillfile")"
      case " $seen " in *" $pskill "*) continue ;; esac
      seen="$seen $pskill"
      ITEMS+=("$pskill"$'\t'"$(skill_desc_of "$skillfile")")
    done < <(find "$path" -maxdepth 4 -name SKILL.md 2>/dev/null | sort)
    group_triage "skills from $short"
  done
fi

ITEMS=()
for dir in "$HOME/.claude/skills" "$PWD/.claude/skills"; do
  [[ -d "$dir" ]] || continue
  while IFS= read -r skillfile; do
    [[ -n "$skillfile" ]] || continue
    ITEMS+=("$(skill_name_of "$skillfile")"$'\t'"$(skill_desc_of "$skillfile")")
  done < <(find "$dir" -maxdepth 2 -name SKILL.md 2>/dev/null | sort)
done
group_triage "your own skills (~/.claude/skills and .claude/skills)"

stage "Built-in tools whose schemas ride along every turn"
say "Each of these is a tool definition in the system prompt, not a skill."
printf '\n'
if confirm "Turn OFF the Artifact tool (publishing pages to claude.ai)?"; then flag enableArtifact false; fi
if confirm "Turn OFF Workflows (multi-agent orchestration scripts)?"; then
  flag enableWorkflows false
  flag workflowKeywordTriggerEnabled false
fi
if confirm "Turn OFF agent view (claude agents, --bg, /background, the daemon)?"; then flag disableAgentView true; fi
if confirm "Turn OFF auto-memory (Claude reading and writing its memory directory)?"; then flag autoMemoryEnabled false; fi
printf '\n'
warn "disableBundledSkills removes ALL shipped skills and workflows at once."
note "Only take it if stage 2 felt like whack-a-mole; plugin and project skills survive it."
if confirm "Set disableBundledSkills: true?"; then flag disableBundledSkills true; fi

stage "MCP servers"
say "MCP tool schemas are usually the heaviest thing in a context window: every tool"
say "from every connected server is described on every turn."
printf '\n'
MCP_NAMES=""
if command -v claude >/dev/null 2>&1; then
  note "asking claude mcp list (health checks can take a few seconds)…"
  MCP_LIST_CMD=(claude mcp list)
  if command -v timeout >/dev/null 2>&1; then MCP_LIST_CMD=(timeout 60 claude mcp list); fi
  MCP_NAMES=$( ("${MCP_LIST_CMD[@]}" 2>/dev/null || true) | grep -E '^[^[:space:]].*: ' | sed 's/: .*//' || true)
fi
if [[ -z "$MCP_NAMES" ]]; then
  say "No MCP servers reported for this directory."
  pause
else
  ITEMS=()
  while IFS= read -r n; do [[ -n "$n" ]] && ITEMS+=("$n"$'\t'"MCP server"); done <<< "$MCP_NAMES"
  i=0
  for row in ${ITEMS[@]+"${ITEMS[@]}"}; do
    i=$((i + 1))
    printf '  %s%2d%s %s%s%s\n' "$BLUE" "$i" "$RESET" "$BOLD" "${row%%$'\t'*}" "$RESET"
  done
  printf '\n'
  warn "This disables them for THIS project only ($PWD), the same as /mcp disable."
  note "Reverse it any time with /mcp enable inside Claude Code."
  pick 'Disable which servers here:'
  for name in ${PICKS[@]+"${PICKS[@]}"}; do
    MCP_DISABLE+=("$name")
    plan_note "MCP server $name → disabled in $PWD"
  done
fi

stage "Custom subagents"
ITEMS=()
for dir in "$HOME/.claude/agents" "$PWD/.claude/agents"; do
  [[ -d "$dir" ]] || continue
  while IFS= read -r f; do
    [[ -n "$f" ]] && ITEMS+=("$f"$'\t'"$(basename "$f")")
  done < <(find "$dir" -maxdepth 1 -name '*.md' 2>/dev/null | sort)
done
if (( ${#ITEMS[@]} == 0 )); then
  say "No custom agent definitions found."
  pause
else
  say "Every agent definition's description is listed to the model on every turn."
  say "There is no off switch, so the wizard moves the file into a disabled/ folder"
  say "next to it. Move it back to restore the agent."
  printf '\n'
  i=0
  for row in ${ITEMS[@]+"${ITEMS[@]}"}; do
    i=$((i + 1))
    printf '  %s%2d%s %s%-28s%s %s%s%s\n' "$BLUE" "$i" "$RESET" "$BOLD" "${row#*$'\t'}" "$RESET" "$DIM" "${row%%$'\t'*}" "$RESET"
  done
  printf '\n'
  pick 'Move which aside:'
  for name in ${PICKS[@]+"${PICKS[@]}"}; do
    AGENT_MOVE+=("$name")
    plan_note "agent $(basename "$name") → moved to disabled/"
  done
fi

stage "Review and apply"
if (( ${#PLANNED[@]} == 0 )); then
  say "Nothing selected — no changes to write."
  pause
else
  say "Staged changes:"
  for p in "${PLANNED[@]}"; do note "  - $p"; done
  printf '\n'
  say "Diff against your current settings:"
  diff -u <(jq -S . "$SETTINGS") <(jq -S . "$PENDING") | tail -n +3 || true
  printf '\n'
  if confirm "Write all of it?"; then
    cp "$SETTINGS" "$SETTINGS.bak-$STAMP"
    cp "$PENDING" "$SETTINGS"
    WROTE=1
    printf '  %s✓ wrote%s %s %s(backup: %s)%s\n' "$GREEN" "$RESET" "$SETTINGS" "$DIM" "$SETTINGS.bak-$STAMP" "$RESET"

    if (( ${#MCP_DISABLE[@]} )) && [[ -f "$CLAUDE_JSON" ]]; then
      cp "$CLAUDE_JSON" "$CLAUDE_JSON.bak-$STAMP"
      tmp=$(mktemp)
      names_json=$(printf '%s\n' "${MCP_DISABLE[@]}" | jq -R . | jq -s .)
      if jq --arg p "$PWD" --argjson names "$names_json" \
          '.projects //= {} | .projects[$p] //= {} | .projects[$p].disabledMcpServers = (((.projects[$p].disabledMcpServers // []) + $names) | unique)' \
          "$CLAUDE_JSON" > "$tmp" && jq -e . "$tmp" >/dev/null; then
        mv "$tmp" "$CLAUDE_JSON"
        printf '  %s✓ disabled%s %s MCP server(s) in %s\n' "$GREEN" "$RESET" "${#MCP_DISABLE[@]}" "$PWD"
      else
        rm -f "$tmp"
        SKIPPED+=("MCP servers: ${MCP_DISABLE[*]} (disable them with /mcp instead)")
        warn "couldn't edit $CLAUDE_JSON; use /mcp inside Claude Code"
      fi
    fi

    for f in ${AGENT_MOVE[@]+"${AGENT_MOVE[@]}"}; do
      mkdir -p "$(dirname "$f")/disabled"
      mv "$f" "$(dirname "$f")/disabled/"
      printf '  %s✓ moved%s %s\n' "$GREEN" "$RESET" "$(basename "$f")"
    done
    pause "Done. Press Enter for the summary."
  else
    say "Nothing written."
    PLANNED=("(discarded — you answered no)")
    pause
  fi
fi

finish
printf '  %s%s%s\n' "$BOLD" "What changed" "$RESET"
for p in ${PLANNED[@]+"${PLANNED[@]}"}; do note "  - $p"; done
printf '\n'
note "Restart Claude Code, then run /context to see the new baseline."
if (( WROTE )); then
  note "Everything here is reversible: /skills, /mcp, or the backup at $SETTINGS.bak-$STAMP"
else
  note "Nothing was written, so nothing needs undoing. Re-run any time."
fi
printf '\n'
